name: Run My Bot
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # هذا يخليك تشغل البوت يدوياً شوكت ما تريد

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Start Bot
        run: python leaderr.py
